/* 
Project Euler Logic problem 2
The Odin Project - JavaScript

Even Fibonacci numbers
Each new term in the Fibonacci sequence is generated by adding the previous 
two terms. By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed 
four million, find the sum of the even-valued terms.
*/

var fibNums = [1,2];
var total = 0;

while(fibNums[fibNums.length-1] < 4000000) {
	fibNums[fibNums.length]=fibNums[fibNums.length-1]+fibNums[fibNums.length-2];
}

for (num in fibNums) {
	if (fibNums[num] % 2 === 0 && fibNums[num] < 4000000) {
		total += fibNums[num];
  }
}

console.log(total);
